"""Generate deterministic ablation feature sets from frame CSV rows."""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from typing import Any
import math

from .feature_csv import MODEL_FEATURE_COLUMNS, is_training_row
from .behavior_features import BEHAVIOR_COLUMNS


_WORLD_PREFIXES = ("pose_world_", "left_hand_world_", "right_hand_world_")


def _is_world_column(column: str) -> bool:
    return column.startswith(_WORLD_PREFIXES)


def _is_lower_pose_column(column: str) -> bool:
    for prefix in ("pose_world_", "pose_"):
        if column.startswith(prefix):
            suffix = column.removeprefix(prefix)
            try:
                return int(suffix[:3]) >= 23
            except ValueError:
                return False
    return False


VARIANT_COLUMNS: dict[str, tuple[str, ...]] = {
    "2d": tuple(
        column
        for column in MODEL_FEATURE_COLUMNS
        if not _is_world_column(column)
        and column.endswith(("_x", "_y"))
    ),
    "2d_quality": tuple(
        column
        for column in MODEL_FEATURE_COLUMNS
        if not _is_world_column(column)
    ),
    "2d_world": tuple(
        column
        for column in MODEL_FEATURE_COLUMNS
        if not column.endswith(("_visibility", "_presence"))
    ),
    "full": MODEL_FEATURE_COLUMNS,
}

_GEOMETRY_POINTS = (0, 11, 12, 13, 14, 15, 16, 23, 24)
_GEOMETRY_COLUMNS = tuple(
    [f"geom_pose_{index:03d}_{axis}" for index in _GEOMETRY_POINTS for axis in ("x", "y")]
    + [
        "geom_scale",
        "geom_scale_valid",
        "geom_left_elbow_angle",
        "geom_right_elbow_angle",
        "geom_torso_angle",
        "geom_shoulder_sin",
        "geom_shoulder_cos",
        "geom_torso_sin",
        "geom_torso_cos",
        "geom_left_wrist_nose_distance",
        "geom_right_wrist_nose_distance",
        "geom_left_wrist_shoulder_distance",
        "geom_right_wrist_shoulder_distance",
    ]
)
VARIANT_COLUMNS["2d_geometry"] = VARIANT_COLUMNS["2d"] + _GEOMETRY_COLUMNS
VARIANT_COLUMNS["2d_world_upper"] = tuple(
    column
    for column in VARIANT_COLUMNS["2d_world"]
    if not _is_lower_pose_column(column)
)

# Object cues intentionally remain outside this behavior-only implementation.
OBJECT_COLUMNS = (
    "phone_conf", "phone_valid", "cheat_sheet_conf", "cheat_sheet_valid",
    "authorized_paper_count", "new_paper_count", "paper_alert",
    "object_valid",
)
VARIANT_COLUMNS["2d_world_behavior"] = VARIANT_COLUMNS["2d_world"] + BEHAVIOR_COLUMNS
VARIANT_COLUMNS["2d_world_object"] = VARIANT_COLUMNS["2d_world"] + OBJECT_COLUMNS
VARIANT_COLUMNS["2d_world_fusion"] = VARIANT_COLUMNS["2d_world"] + BEHAVIOR_COLUMNS + OBJECT_COLUMNS

# Behavior-only workflow defaults. Object variants remain legacy definitions
# for compatibility, but are never generated by default in this task.
DEFAULT_VARIANTS = (
    "2d", "2d_quality", "2d_world", "full", "2d_geometry",
    "2d_world_upper", "2d_world_behavior",
)

METADATA_COLUMNS = (
    "split",
    "split_group",
    "camera_view_id",
    "source_filename",
    "source_path",
    "sequence_id",
    "class_code",
    "label",
    "status",
    "frame_id",
    "timestamp_ms",
    "track_id",
    "target_state",
    "protocol",
    "interval_used_for_features",
    "video_class_code",
    "actor_id",
    "action_actor_id",
    "peer_actor_id",
    "actor_role",
    "track_side",
    "is_action_actor",
)


def feature_columns_for_variant(variant: str) -> tuple[str, ...]:
    """Return the stable model-column order for one named variant."""

    try:
        return VARIANT_COLUMNS[variant]
    except KeyError as error:
        raise ValueError(f"unknown feature variant: {variant}") from error


def _finite_number(value: Any) -> float:
    if value is None or value == "":
        return 0.0
    try:
        number = float(value)
    except (TypeError, ValueError):
        return 0.0
    return number if number == number and abs(number) != float("inf") else 0.0


def _geometry(row: Mapping[str, Any]) -> dict[str, float]:
    def point(index: int) -> tuple[float, float]:
        return (_finite_number(row.get(f"pose_{index:03d}_x")), _finite_number(row.get(f"pose_{index:03d}_y")))

    points = {index: point(index) for index in _GEOMETRY_POINTS}
    shoulder_mid = ((points[11][0] + points[12][0]) / 2, (points[11][1] + points[12][1]) / 2)
    shoulder_dx = points[12][0] - points[11][0]
    shoulder_dy = points[12][1] - points[11][1]
    scale = math.hypot(shoulder_dx, shoulder_dy)
    scale_valid = float(scale > 1e-6)
    divisor = scale if scale_valid else 1.0

    def normalized(index: int, axis: int) -> float:
        return (points[index][axis] - shoulder_mid[axis]) / divisor

    def angle(a: int, b: int, c: int) -> float:
        ux, uy = points[a][0] - points[b][0], points[a][1] - points[b][1]
        vx, vy = points[c][0] - points[b][0], points[c][1] - points[b][1]
        return math.atan2(abs(ux * vy - uy * vx), ux * vx + uy * vy) / math.pi

    def distance(a: int, b: int) -> float:
        return math.hypot(points[a][0] - points[b][0], points[a][1] - points[b][1]) / divisor

    shoulder_angle = math.atan2(shoulder_dy, shoulder_dx)
    torso_dx = shoulder_mid[0] - ((points[23][0] + points[24][0]) / 2)
    torso_dy = shoulder_mid[1] - ((points[23][1] + points[24][1]) / 2)
    torso_angle = math.atan2(torso_dy, torso_dx)
    output = {f"geom_pose_{index:03d}_{axis}": normalized(index, axis_index) for index in _GEOMETRY_POINTS for axis, axis_index in (("x", 0), ("y", 1))}
    output.update({
        "geom_scale": scale,
        "geom_scale_valid": scale_valid,
        "geom_left_elbow_angle": angle(11, 13, 15),
        "geom_right_elbow_angle": angle(12, 14, 16),
        "geom_torso_angle": torso_angle / math.pi,
        "geom_shoulder_sin": math.sin(shoulder_angle),
        "geom_shoulder_cos": math.cos(shoulder_angle),
        "geom_torso_sin": math.sin(torso_angle),
        "geom_torso_cos": math.cos(torso_angle),
        "geom_left_wrist_nose_distance": distance(15, 0),
        "geom_right_wrist_nose_distance": distance(16, 0),
        "geom_left_wrist_shoulder_distance": distance(15, 11),
        "geom_right_wrist_shoulder_distance": distance(16, 12),
    })
    return output


def geometry_features(row: Mapping[str, Any]) -> dict[str, float]:
    return _geometry(row)


def generate_feature_variant(
    rows: Iterable[Mapping[str, Any]],
    *,
    variant: str,
    exclude_predicted: bool = True,
) -> list[dict[str, Any]]:
    """Project frame rows into one finite, metadata-preserving feature schema."""

    columns = feature_columns_for_variant(variant)
    output: list[dict[str, Any]] = []
    for row in rows:
        if exclude_predicted and not is_training_row(row):
            continue
        projected = {
            key: row.get(key)
            for key in METADATA_COLUMNS
            if key in row
        }
        projected.update({column: _finite_number(row.get(column)) for column in columns})
        if variant == "2d_geometry":
            projected.update(_geometry(row))
        output.append(projected)
    return output


def generate_feature_variants(
    rows: Iterable[Mapping[str, Any]],
    *,
    exclude_predicted: bool = True,
) -> dict[str, list[dict[str, Any]]]:
    """Generate all four locked feature variants from the same input rows."""

    materialized = list(rows)
    return {
        variant: generate_feature_variant(
            materialized,
            variant=variant,
            exclude_predicted=exclude_predicted,
        )
        for variant in DEFAULT_VARIANTS
    }


__all__ = [
    "METADATA_COLUMNS",
    "VARIANT_COLUMNS",
    "DEFAULT_VARIANTS",
    "feature_columns_for_variant",
    "generate_feature_variant",
    "generate_feature_variants",
    "geometry_features",
]
